# Generated by Django 5.2.9 on 2025-12-31 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analysis_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_url', models.URLField(max_length=500)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('facts', 'Facts JSON'), ('screenshot', 'Screenshot'), ('docx', 'DOCX Document')], max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='projects.analysisrun')),
            ],
            options={
                'db_table': 'artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('course', 'Course Work'), ('diploma', 'Diploma')], default='course', max_length=20)),
                ('language', models.CharField(default='ru-RU', max_length=10)),
                ('target_pages', models.IntegerField(default=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.analysisrun')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='projects.project'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('outline', 'Outline'), ('theory', 'Theory'), ('practice', 'Practice'), ('conclusion', 'Conclusion')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True, help_text='200-300 words summary for next section context')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.document')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['project', 'commit_sha'], name='analysis_ru_project_77bef8_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['status'], name='analysis_ru_status_30052f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('document', 'key')},
        ),
    ]
