# Generated by Django 5.2.9 on 2025-12-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_analysisrun_progress_alter_analysisrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='schema_version',
            field=models.CharField(default='v1', help_text='Schema version for forward compatibility', max_length=10),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['kind', 'schema_version'], name='artifacts_kind_962191_idx'),
        ),
    ]
