# Generated by Django 5.2.9 on 2026-01-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_section_key_remove_choices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentartifact',
            new_name='document_ar_documen_2b6a8e_idx',
            old_name='document_ar_documen_7e2a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='documentartifact',
            new_name='document_ar_section_e379f3_idx',
            old_name='document_ar_section_b4c3e2_idx',
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='analyzer_version',
            field=models.CharField(default='v1', max_length=16),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='artifact',
            name='hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='version',
            field=models.CharField(default='v1', max_length=16),
        ),
        migrations.AddField(
            model_name='documentartifact',
            name='hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='documentartifact',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='documentartifact',
            name='version',
            field=models.CharField(default='v1', max_length=16),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('facts', 'Facts JSON'), ('screenshot', 'Screenshot'), ('docx', 'DOCX Document'), ('meta', 'Meta Info'), ('trace', 'Trace Info'), ('errors', 'Errors Info')], max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='schema_version',
            field=models.CharField(default='v1', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='summary_current',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['fingerprint'], name='analysis_ru_fingerp_b2226b_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['analysis_run', 'kind', 'hash'], name='artifacts_analysi_ef018e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentartifact',
            index=models.Index(fields=['document', 'kind', 'hash'], name='document_ar_documen_25c237_idx'),
        ),
    ]
