# Generated by Django 5.2.9 on 2026-01-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_fingerprint_hash_trace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentartifact',
            name='kind',
            field=models.CharField(choices=[('outline', 'Outline JSON'), ('section_text', 'Section Text'), ('section_summary', 'Section Summary'), ('context_pack', 'Context Pack'), ('trace', 'Generation Trace')], max_length=32),
        ),
    ]
