# Generated by Django 5.2.9 on 2026-01-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_add_llm_trace_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('editing', 'Editing'), ('finalized', 'Finalized'), ('error', 'Error')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentartifact',
            name='kind',
            field=models.CharField(choices=[('outline', 'Outline JSON'), ('section_text', 'Section Text'), ('section_summary', 'Section Summary'), ('context_pack', 'Context Pack'), ('trace', 'Generation Trace'), ('llm_trace', 'LLM Call Trace'), ('edit_plan', 'Edit Plan'), ('quality_report', 'Quality Report'), ('glossary', 'Glossary'), ('consistency_report', 'Consistency Report'), ('chapter_conclusions', 'Chapter Conclusions'), ('transitions', 'Transitions'), ('section_edited', 'Section Edited'), ('document_edited', 'Document Edited')], max_length=32),
        ),
    ]
