# Generated by Django 5.2.9 on 2026-01-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_add_editor_artifact_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentartifact',
            name='kind',
            field=models.CharField(choices=[('outline', 'Outline JSON'), ('section_text', 'Section Text'), ('section_summary', 'Section Summary'), ('context_pack', 'Context Pack'), ('trace', 'Generation Trace'), ('llm_trace', 'LLM Call Trace'), ('edit_plan', 'Edit Plan'), ('quality_report', 'Quality Report'), ('edit_quality_report', 'Edit Quality Report'), ('glossary', 'Glossary'), ('consistency_report', 'Consistency Report'), ('chapter_conclusions', 'Chapter Conclusions'), ('transitions', 'Transitions'), ('section_edited', 'Section Edited'), ('document_edited', 'Document Edited')], max_length=32),
        ),
    ]
