# Generated by Django 5.2.9 on 2026-01-03 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_documentartifact_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_type', models.CharField(choices=[('referat', 'Реферат'), ('diploma', 'Диплом'), ('course', 'Курсовая')], default='course', max_length=20)),
                ('topic_title', models.CharField(max_length=500)),
                ('topic_description', models.TextField(blank=True)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('target_pages_min', models.IntegerField(default=20)),
                ('target_pages_max', models.IntegerField(default=40)),
                ('style_level', models.IntegerField(default=1)),
                ('constraints', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_stage',
            field=models.CharField(choices=[('outline', 'Outline'), ('generation', 'Generation'), ('enrichment', 'Enrichment'), ('editing', 'Editing'), ('finalization', 'Finalization')], default='outline', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='chapter_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='depth',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='section',
            name='edited_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='enriched_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('enriching', 'Enriching'), ('editing', 'Editing'), ('finalized', 'Finalized'), ('error', 'Error')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('referat', 'Referat'), ('course', 'Course Work'), ('diploma', 'Diploma')], default='course', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentartifact',
            name='kind',
            field=models.CharField(choices=[('outline', 'Outline JSON'), ('document_profile', 'Document Profile'), ('section_text', 'Section Text'), ('section_summary', 'Section Summary'), ('section_enriched', 'Section Enriched'), ('context_pack', 'Context Pack'), ('trace', 'Generation Trace'), ('llm_trace', 'LLM Call Trace'), ('edit_plan', 'Edit Plan'), ('quality_report', 'Quality Report'), ('edit_quality_report', 'Edit Quality Report'), ('glossary', 'Glossary'), ('consistency_report', 'Consistency Report'), ('chapter_conclusions', 'Chapter Conclusions'), ('transitions', 'Transitions'), ('section_edited', 'Section Edited'), ('document_edited', 'Document Edited'), ('document_draft', 'Document Draft'), ('toc', 'Table of Contents'), ('literature', 'Literature List')], max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.documentprofile'),
        ),
    ]
