# Generated by Django 5.2.9 on 2026-01-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_add_document_profile_and_pipeline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='parent_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
