ANALYZER_VERSION = "v1"
FACTS_SCHEMA = "facts.v1"

SKIP_DIRS = {
    "node_modules", "vendor", ".git", "__pycache__", "venv", ".venv",
    "env", "dist", "build", "eggs", ".eggs", ".tox", "htmlcov",
    ".next", ".nuxt", "coverage", ".cache", ".pytest_cache", ".mypy_cache"
}

EXTENSION_TO_LANG = {
    ".py": "Python",
    ".js": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".jsx": "JavaScript",
    ".go": "Go",
    ".java": "Java",
    ".rs": "Rust",
    ".rb": "Ruby",
    ".php": "PHP",
    ".cs": "C#",
    ".cpp": "C++",
    ".c": "C",
    ".swift": "Swift",
    ".kt": "Kotlin",
    ".vue": "Vue",
    ".svelte": "Svelte",
}

PYTHON_FRAMEWORKS = {
    "django": ("Django", "web"),
    "fastapi": ("FastAPI", "web"),
    "flask": ("Flask", "web"),
    "celery": ("Celery", "task-queue"),
    "pytest": ("pytest", "testing"),
    "sqlalchemy": ("SQLAlchemy", "orm"),
    "pydantic": ("Pydantic", "validation"),
    "alembic": ("Alembic", "migrations"),
    "uvicorn": ("Uvicorn", "server"),
    "gunicorn": ("Gunicorn", "server"),
    "aiohttp": ("aiohttp", "web"),
    "starlette": ("Starlette", "web"),
}

JS_FRAMEWORKS = {
    "react": ("React", "frontend"),
    "vue": ("Vue.js", "frontend"),
    "angular": ("Angular", "frontend"),
    "svelte": ("Svelte", "frontend"),
    "next": ("Next.js", "fullstack"),
    "nuxt": ("Nuxt.js", "fullstack"),
    "express": ("Express", "backend"),
    "nestjs": ("NestJS", "backend"),
    "fastify": ("Fastify", "backend"),
    "tailwindcss": ("TailwindCSS", "styling"),
    "redux": ("Redux", "state-management"),
    "zustand": ("Zustand", "state-management"),
    "pinia": ("Pinia", "state-management"),
    "prisma": ("Prisma", "orm"),
    "typeorm": ("TypeORM", "orm"),
    "axios": ("Axios", "http-client"),
}

DEEP_ROLE_MAPPING = {
    "routers": "api-routing",
    "routes": "api-routing",
    "router": "routing",
    "controllers": "controllers",
    "models": "orm-models",
    "schemas": "data-schemas",
    "services": "business-logic",
    "repositories": "data-access",
    "utils": "utilities",
    "helpers": "utilities",
    "middleware": "middleware",
    "middlewares": "middleware",
    "auth": "authentication",
    "users": "user-management",
    "components": "ui-components",
    "pages": "pages",
    "views": "views",
    "stores": "state-management",
    "store": "state-management",
    "hooks": "react-hooks",
    "composables": "vue-composables",
    "api": "api-client",
    "config": "configuration",
    "constants": "constants",
    "types": "type-definitions",
    "interfaces": "type-definitions",
    "tests": "testing",
    "migrations": "migrations",
    "templates": "templates",
    "static": "static-files",
    "public": "static-files",
    "assets": "assets",
    "styles": "styles",
    "css": "styles",
}
