# Generated by Django 5.2.9 on 2026-01-01 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_calls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model', 'status'], name='llm_calls_model_42be09_idx')],
            },
        ),
    ]
